version: "3"
services:
  php:
    image: php:fpm-alpine
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor:ro
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./public:/usr/share/nginx/html
      - .docker/web/default.conf:/etc/nginx/conf.d/default.conf
  mercure:
    image: dunglas/mercure
    env_file:
      - .env
